version: '3'  

volumes:
  lixeira-vol:

services:

  applixeira:
    image: app-lixeira
    tty: true        # docker run -t
    restart: on-failure
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile.lixeira
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/root/.Xauthority
