version: '3'  

services:

  appcaminhao:
    image: app-caminhao
    tty: true        # docker run -t
    privileged: true
    build: 
      context: .
      dockerfile: Dockerfile.caminhao
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/root/.Xauthority
